# ┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
# ┃ utils: init                                                                                      ┃
# ┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛

from .decorators import jwt_role_required, get_current_user, cache_response
from .validators import (
    validate_email,
    validate_password,
    validate_cgpa,
    validate_phone,
    validate_url,
    sanitize_string,
    validate_file_extension,
    validate_resume_filename,
    validate_logo_filename,
)
from .helpers import (
    paginate_query,
    generate_unique_filename,
    get_client_ip,
    format_datetime,
    safe_int,
    safe_float,
    ensure_dir,
)
from .constants import (
    USER_ROLES,
    USER_STATUSES,
    JOB_STATUSES,
    APPLICATION_STATUSES,
    PLACEMENT_STATUSES,
    ALLOWED_RESUME_EXTENSIONS,
    ALLOWED_LOGO_EXTENSIONS,
    MAX_RESUME_SIZE_MB,
    MAX_LOGO_SIZE_MB,
    CACHE_TTL_SHORT,
    CACHE_TTL_MEDIUM,
    CACHE_TTL_LONG,
)
from .exceptions import (
    AppError,
    ValidationError,
    AuthorizationError,
    NotFoundError,
    ConflictError,
)
from .security import (
    generate_secure_token,
    hash_file,
    is_safe_path,
)
from .dirs import (
    ensure_directories,
    dir_backend,
    dir_instance,
    dir_exports,
    dir_reports,
    dir_backups,
    dir_temporary,
    dir_storage,
    dir_public,
    dir_private,
    dir_uploads,
    dir_logos,
    dir_resumes,
    dir_offer_letters,
    dir_docs,
    dir_company_docs,
    dir_student_docs,
    # string versions
    dir_exports_str,
    dir_reports_str,
    dir_uploads_str,
    dir_logos_str,
    dir_resumes_str,
    dir_offer_letters_str,
    dir_docs_str,
    dir_company_docs_str,
    dir_student_docs_str,
    dir_storage_str,
    dir_public_str,
    dir_private_str,
    dir_temporary_str,
    dir_backups_str,
)
from .email import send_email

__all__ = [
    # decorators
    "jwt_role_required",
    "get_current_user",
    "cache_response",
    # validators
    "validate_email",
    "validate_password",
    "validate_cgpa",
    "validate_phone",
    "validate_url",
    "sanitize_string",
    "validate_file_extension",
    "validate_resume_filename",
    "validate_logo_filename",
    # helpers
    "paginate_query",
    "generate_unique_filename",
    "get_client_ip",
    "format_datetime",
    "safe_int",
    "safe_float",
    "ensure_dir",
    # constants
    "USER_ROLES",
    "USER_STATUSES",
    "JOB_STATUSES",
    "APPLICATION_STATUSES",
    "PLACEMENT_STATUSES",
    "ALLOWED_RESUME_EXTENSIONS",
    "ALLOWED_LOGO_EXTENSIONS",
    "MAX_RESUME_SIZE_MB",
    "MAX_LOGO_SIZE_MB",
    "CACHE_TTL_SHORT",
    "CACHE_TTL_MEDIUM",
    "CACHE_TTL_LONG",
    # exceptions
    "AppError",
    "ValidationError",
    "AuthorizationError",
    "NotFoundError",
    "ConflictError",
    # security
    "generate_secure_token",
    "hash_file",
    "is_safe_path",
    # dirs
    "ensure_directories",
    "dir_backend",
    "dir_instance",
    "dir_exports",
    "dir_reports",
    "dir_backups",
    "dir_temporary",
    "dir_storage",
    "dir_public",
    "dir_private",
    "dir_uploads",
    "dir_logos",
    "dir_resumes",
    "dir_offer_letters",
    "dir_docs",
    "dir_company_docs",
    "dir_student_docs",
    "dir_exports_str",
    "dir_reports_str",
    "dir_uploads_str",
    "dir_logos_str",
    "dir_resumes_str",
    "dir_offer_letters_str",
    "dir_docs_str",
    "dir_company_docs_str",
    "dir_student_docs_str",
    "dir_storage_str",
    "dir_public_str",
    "dir_private_str",
    "dir_temporary_str",
    "dir_backups_str",
    # email
    "send_email",
]
